services:
  - type: web
    name: go-up
    env: php
    buildCommand: |
      chmod +x render_build.sh
      ./render_build.sh
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://go-up.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: LOG_CHANNEL
        value: stderr
    disk:
      name: storage
      mountPath: /var/www/html/storage
      sizeGB: 1
